// lib/mock-data.ts
import { CCTV, TicketReport, UserAccount } from '@/types/cctv';

export const initialCCTVs: CCTV[] = [
  {
    id: 'cctv-1',
    code: 'CAM-MB-01',
    location: 'Main Building',
    floor: 'LT1',
    cameraType: 'Dome 4MP',
    ipAddress: '192.168.10.11',
    status: 'normal',
    damageNotes: 'Tidak Ada (Operasional Normal)',
    followUpPlan: 'Pemeliharaan Rutin Bulanan',
    lastChecked: '2026-10-07',
  },
  {
    id: 'cctv-2',
    code: 'CAM-CT-01',
    location: 'Caffe Toya',
    floor: 'GF',
    cameraType: 'Bullet Outdoor 5MP',
    ipAddress: '192.168.10.12',
    status: 'broken',
    damageNotes: 'Gambar No-Signal, Adaptor Mati',
    followUpPlan: 'Penggantian Power Supply 12V 2A',
    lastChecked: '2026-10-07',
  },
  {
    id: 'cctv-3',
    code: 'CAM-VIL-01',
    location: 'Villa',
    floor: 'GF',
    cameraType: 'Dome IR 2MP',
    ipAddress: '192.168.10.21',
    status: 'normal',
    damageNotes: 'Tidak Ada',
    followUpPlan: 'Monitoring Rutin',
    lastChecked: '2026-10-06',
  },
  {
    id: 'cctv-4',
    code: 'CAM-KS-01',
    location: 'Kitchen Samiya',
    floor: 'GF',
    cameraType: 'PTZ Speed Dome 360',
    ipAddress: '192.168.20.05',
    status: 'maintenance',
    damageNotes: 'Lensa Buram Kena Uap Minyak',
    followUpPlan: 'Pembersihan Lensa & Re-Housing Protection',
    lastChecked: '2026-10-07',
  },
  {
    id: 'cctv-5',
    code: 'CAM-HWB-01',
    location: 'HWB',
    floor: 'Rooftop',
    cameraType: 'Bullet Outdoor 5MP',
    ipAddress: '192.168.30.12',
    status: 'normal',
    damageNotes: 'Tidak Ada',
    followUpPlan: 'Pengecekan Fisik Rutin',
    lastChecked: '2026-10-07',
  },
];

export const initialTickets: TicketReport[] = [
  {
    id: 'TKT-1001',
    cctvId: 'cctv-2',
    cctvCode: 'CAM-CT-01',
    location: 'Caffe Toya',
    floor: 'GF',
    reporterName: 'Wayan Security',
    issueType: 'Gambar No-Signal / Mati',
    description: 'Kamera mati total saat pergantian shift malam.',
    status: 'pending',
    reportedAt: '2026-10-07',
  },
  {
    id: 'TKT-1002',
    cctvId: 'cctv-4',
    cctvCode: 'CAM-KS-01',
    location: 'Kitchen Samiya',
    floor: 'GF',
    reporterName: 'Kadek Security',
    issueType: 'Lensa Buram / Kotor',
    description: 'Tampilan buram akibat paparan uap area dapur.',
    status: 'in_progress',
    reportedAt: '2026-10-06',
  },
];

export const initialUsers: UserAccount[] = [
  {
    id: 'usr-1',
    username: 'admin',
    name: 'Admin IT Principal',
    email: 'admin.it@hommsaranam.com',
    role: 'admin',
    department: 'IT & Engineering',
    status: 'active',
    createdAt: '2026-01-10',
  },
  {
    id: 'usr-2',
    username: 'security01',
    name: 'I Made Security',
    email: 'made.security@hommsaranam.com',
    role: 'staff',
    department: 'Security Operational',
    status: 'active',
    createdAt: '2026-02-15',
  },
  {
    id: 'usr-3',
    username: 'security02',
    name: 'Wayan Patrol',
    email: 'wayan.patrol@hommsaranam.com',
    role: 'staff',
    department: 'Security Operational',
    status: 'active',
    createdAt: '2026-03-01',
  },
];